version: '3'

services:

    db:
        image: postgres
        container_name: "postgres_container"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: chatbot 
        volumes:
            - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
        ports:
            - 5432:5432

    chatbot_parser:
        build: ./chatbot_parser
        container_name: "chatbot_parser"
        ports: 
          - 5050:5050
        depends_on:
            - db

    shrug_command:
        build: ./shrug_command
        container_name: "shrug_command"
        ports: 
          - 5051:5051
        depends_on:
            - db
    
    email_command:
        build: ./email_command
        container_name: "email_command"
        image: email-service-image
        ports:
            - 5052:5052
        environment:
           - SENDGRID_FROM_EMAIL=XXX_INPUT_SENDGRID_FROM_EMAILXXX
           - SENDGRID_API_KEY=XXXINPUT_SENDGRID_KEYXXX
        
    